[package]
name = "deepwyrm-kernel"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
path = "src/lib.rs"

[features]
default = []
test-support = []

[[bin]]
name = "deepwyrm-kernel"
path = "src/main.rs"
test = false
bench = false

[dependencies]
deepwyrm-abi = { path = "../crates/deepwyrm-abi" }
