use super::*;

pub(super) fn render(model: &Model) -> Result<BTreeMap<String, String>> {
    let mut outputs = BTreeMap::new();
    outputs.insert("deepwyrm_abi.rs".to_owned(), render_rust(model)?);
    outputs.insert("deepwyrm_abi.h".to_owned(), render_c(model)?);
    outputs.insert(
        "syscall_dispatch.rs".to_owned(),
        render_dispatch_metadata(model)?,
    );
    outputs.insert(
        "syscall_kernel.rs".to_owned(),
        render_kernel_dispatch(model)?,
    );
    outputs.insert(
        "syscall_wrappers.rs".to_owned(),
        render_wrapper_metadata(model)?,
    );
    outputs.insert(
        "syscall_veneer_x86_64.S".to_owned(),
        render_x86_64_syscall_veneer(model)?,
    );
    outputs.insert("ABI.md".to_owned(), render_markdown(model)?);
    outputs.insert("README.md".to_owned(), render_readme());
    for contents in outputs.values_mut() {
        contents.truncate(contents.trim_end().len());
        contents.push('\n');
    }
    Ok(outputs)
}

pub(super) fn generated_preamble(comment: &str) -> String {
    format!(
        "{comment} @generated by abi-gen from abi/schema.\n{comment} Do not edit this file directly.\n\n"
    )
}

pub(super) fn render_rust(model: &Model) -> Result<String> {
    let mut out = generated_preamble("//");
    writeln!(out, "/// Native Deepwyrm ABI version.").unwrap();
    writeln!(
        out,
        "pub const DW_ABI_VERSION: u32 = {};\n",
        model.abi.version
    )
    .unwrap();

    for item in &model.newtypes {
        writeln!(out, "/// {}", item.doc).unwrap();
        writeln!(out, "#[repr(transparent)]").unwrap();
        writeln!(
            out,
            "#[derive(Clone, Copy, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]"
        )
        .unwrap();
        writeln!(out, "pub struct {}(pub {});\n", item.name, item.base).unwrap();
    }

    for set in &model.value_sets {
        for item in &set.values {
            writeln!(out, "/// {}", item.doc).unwrap();
            writeln!(
                out,
                "pub const {}_{}: {} = {}({});\n",
                set.prefix, item.name, set.rust_type, set.rust_type, item.value
            )
            .unwrap();
        }
    }
    writeln!(out, "/// Mask of every DwRights bit known to ABI 0.").unwrap();
    writeln!(
        out,
        "pub const DW_RIGHTS_KNOWN_MASK: DwRights = DwRights({});\n",
        model.known_rights_mask
    )
    .unwrap();
    for entry in &model.object_rights {
        writeln!(
            out,
            "/// Compatible rights for the {} object type.",
            entry.object
        )
        .unwrap();
        writeln!(
            out,
            "pub const DW_OBJECT_COMPATIBLE_RIGHTS_{}: DwRights = DwRights({});\n",
            entry.object, entry.mask
        )
        .unwrap();
    }
    writeln!(out, "/// Returns the compatible-rights mask for one object type; sentinel, reserved, and unknown types return zero.").unwrap();
    writeln!(
        out,
        "pub const fn dw_object_compatible_rights(object_type: DwObjectType) -> DwRights {{"
    )
    .unwrap();
    writeln!(out, "    match object_type.0 {{").unwrap();
    for entry in &model.object_rights {
        writeln!(
            out,
            "        {} => DW_OBJECT_COMPATIBLE_RIGHTS_{},",
            entry.object_value, entry.object
        )
        .unwrap();
    }
    writeln!(out, "        _ => DwRights(0),").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}\n").unwrap();
    writeln!(out, "/// Returns true when a rights value contains only ABI-known bits; zero is structurally known.").unwrap();
    writeln!(
        out,
        "pub const fn dw_rights_are_known(rights: DwRights) -> bool {{"
    )
    .unwrap();
    writeln!(out, "    rights.0 & !DW_RIGHTS_KNOWN_MASK.0 == 0").unwrap();
    writeln!(out, "}}\n").unwrap();
    writeln!(out, "/// Returns true when all bits are compatible with the object type; zero is structurally compatible.").unwrap();
    writeln!(out, "pub const fn dw_rights_are_compatible(object_type: DwObjectType, rights: DwRights) -> bool {{").unwrap();
    writeln!(
        out,
        "    let compatible = dw_object_compatible_rights(object_type);"
    )
    .unwrap();
    writeln!(out, "    rights.0 & !compatible.0 == 0").unwrap();
    writeln!(out, "}}\n").unwrap();
    writeln!(out, "/// Mask of every DwSignals bit known to ABI 0.").unwrap();
    writeln!(
        out,
        "pub const DW_SIGNALS_KNOWN_MASK: DwSignals = DwSignals({});\n",
        model.known_signals_mask
    )
    .unwrap();
    for entry in &model.object_signals {
        writeln!(
            out,
            "/// Applicable wait signals for the {} object type.",
            entry.object
        )
        .unwrap();
        writeln!(
            out,
            "pub const DW_OBJECT_COMPATIBLE_SIGNALS_{}: DwSignals = DwSignals({});\n",
            entry.object, entry.mask
        )
        .unwrap();
    }
    writeln!(out, "/// Returns the applicable wait-signal mask for one object type; sentinel, reserved, and unknown types return zero.").unwrap();
    writeln!(
        out,
        "pub const fn dw_object_compatible_signals(object_type: DwObjectType) -> DwSignals {{"
    )
    .unwrap();
    writeln!(out, "    match object_type.0 {{").unwrap();
    for entry in &model.object_signals {
        writeln!(
            out,
            "        {} => DW_OBJECT_COMPATIBLE_SIGNALS_{},",
            entry.object_value, entry.object
        )
        .unwrap();
    }
    writeln!(out, "        _ => DwSignals(0),").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}\n").unwrap();
    writeln!(out, "/// Returns true when a signal mask contains only ABI-known bits; zero is structurally known.").unwrap();
    writeln!(
        out,
        "pub const fn dw_signals_are_known(signals: DwSignals) -> bool {{"
    )
    .unwrap();
    writeln!(out, "    signals.0 & !DW_SIGNALS_KNOWN_MASK.0 == 0").unwrap();
    writeln!(out, "}}\n").unwrap();
    writeln!(out, "/// Returns true when every requested signal applies to the object type; zero is structurally compatible.").unwrap();
    writeln!(out, "pub const fn dw_signals_are_compatible(object_type: DwObjectType, signals: DwSignals) -> bool {{").unwrap();
    writeln!(
        out,
        "    let compatible = dw_object_compatible_signals(object_type);"
    )
    .unwrap();
    writeln!(out, "    signals.0 & !compatible.0 == 0").unwrap();
    writeln!(out, "}}\n").unwrap();
    for constant in &model.constants {
        writeln!(out, "/// {}", constant.doc).unwrap();
        writeln!(
            out,
            "pub const {}: {} = {};\n",
            constant.name,
            constant.ty,
            rust_value(&constant.ty, constant.value, &model.newtypes)
        )
        .unwrap();
    }
    for syscall in &model.syscalls {
        writeln!(out, "/// {}", syscall.doc).unwrap();
        writeln!(
            out,
            "pub const DW_SYSCALL_{}: DwSyscallId = DwSyscallId(0x{:08x});\n",
            syscall.name.to_ascii_uppercase(),
            syscall.number
        )
        .unwrap();
    }

    for record in &model.records {
        writeln!(out, "/// {}", record.doc).unwrap();
        writeln!(out, "#[repr(C)]").unwrap();
        writeln!(out, "#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]").unwrap();
        writeln!(out, "pub struct {} {{", record.name).unwrap();
        for field in &record.fields {
            writeln!(out, "    /// {}", field.doc).unwrap();
            writeln!(out, "    pub {}: {},", field.name, field.ty.rust()).unwrap();
        }
        writeln!(out, "}}\n").unwrap();
        writeln!(
            out,
            "pub const {}: u32 = {};\n",
            record_size_constant(&record.name),
            record.size
        )
        .unwrap();
    }

    writeln!(out, "#[cfg(test)]").unwrap();
    writeln!(out, "mod generated_layout_tests {{").unwrap();
    writeln!(out, "    use super::*;").unwrap();
    writeln!(
        out,
        "    use core::mem::{{align_of, offset_of, size_of}};\n"
    )
    .unwrap();
    writeln!(out, "    #[test]").unwrap();
    writeln!(out, "    fn scalar_layouts_match_schema() {{").unwrap();
    let layouts = type_layouts(&model.newtypes);
    for item in &model.newtypes {
        let (size, align) = layouts[&item.name];
        writeln!(
            out,
            "        assert_eq!(size_of::<{}>(), {});",
            item.name, size
        )
        .unwrap();
        writeln!(
            out,
            "        assert_eq!(align_of::<{}>(), {});",
            item.name, align
        )
        .unwrap();
    }
    writeln!(out, "    }}\n").unwrap();
    writeln!(out, "    #[test]").unwrap();
    writeln!(out, "    fn record_layouts_match_schema() {{").unwrap();
    for record in &model.records {
        writeln!(
            out,
            "        assert_eq!(size_of::<{}>(), {});",
            record.name, record.size
        )
        .unwrap();
        writeln!(
            out,
            "        assert_eq!(align_of::<{}>(), {});",
            record.name, record.align
        )
        .unwrap();
        for (field, offset) in record.fields.iter().zip(&record.offsets) {
            writeln!(
                out,
                "        assert_eq!(offset_of!({}, {}), {});",
                record.name, field.name, offset
            )
            .unwrap();
        }
    }
    writeln!(out, "    }}\n").unwrap();
    writeln!(out, "    #[test]").unwrap();
    writeln!(out, "    fn fundamental_constants_match_schema() {{").unwrap();
    writeln!(out, "        assert_eq!(DW_HANDLE_INVALID.0, 0);").unwrap();
    writeln!(
        out,
        "        assert_eq!(DW_ABI_VERSION, {});",
        model.abi.version
    )
    .unwrap();
    for set in &model.value_sets {
        for item in &set.values {
            writeln!(
                out,
                "        assert_eq!({}_{}.0, {});",
                set.prefix, item.name, item.value
            )
            .unwrap();
        }
    }
    writeln!(
        out,
        "        assert_eq!(DW_RIGHTS_KNOWN_MASK.0, {});",
        model.known_rights_mask
    )
    .unwrap();
    for entry in &model.object_rights {
        writeln!(
            out,
            "        assert_eq!(DW_OBJECT_COMPATIBLE_RIGHTS_{}.0, {});",
            entry.object, entry.mask
        )
        .unwrap();
        writeln!(
            out,
            "        assert_eq!(dw_object_compatible_rights(DW_OBJECT_TYPE_{}).0, {});",
            entry.object, entry.mask
        )
        .unwrap();
    }
    writeln!(
        out,
        "        assert_eq!(dw_object_compatible_rights(DW_OBJECT_TYPE_NONE).0, 0);"
    )
    .unwrap();
    writeln!(
        out,
        "        assert!(dw_rights_are_known(DW_RIGHTS_KNOWN_MASK));"
    )
    .unwrap();
    writeln!(
        out,
        "        assert!(dw_rights_are_compatible(DW_OBJECT_TYPE_MEMORY_OBJECT, DW_RIGHT_MAP));"
    )
    .unwrap();
    writeln!(
        out,
        "        assert!(!dw_rights_are_compatible(DW_OBJECT_TYPE_TASK_GROUP, DW_RIGHT_READ));"
    )
    .unwrap();
    writeln!(
        out,
        "        assert_eq!(DW_SIGNALS_KNOWN_MASK.0, {});",
        model.known_signals_mask
    )
    .unwrap();
    for entry in &model.object_signals {
        writeln!(
            out,
            "        assert_eq!(DW_OBJECT_COMPATIBLE_SIGNALS_{}.0, {});",
            entry.object, entry.mask
        )
        .unwrap();
        writeln!(
            out,
            "        assert_eq!(dw_object_compatible_signals(DW_OBJECT_TYPE_{}).0, {});",
            entry.object, entry.mask
        )
        .unwrap();
    }
    writeln!(
        out,
        "        assert_eq!(dw_object_compatible_signals(DW_OBJECT_TYPE_NONE).0, 0);"
    )
    .unwrap();
    writeln!(
        out,
        "        assert!(dw_signals_are_known(DW_SIGNALS_KNOWN_MASK));"
    )
    .unwrap();
    writeln!(
        out,
        "        assert!(dw_signals_are_compatible(DW_OBJECT_TYPE_CHANNEL, DW_SIGNAL_READABLE));"
    )
    .unwrap();
    writeln!(
        out,
        "        assert!(!dw_signals_are_compatible(DW_OBJECT_TYPE_EVENT, DW_SIGNAL_READABLE));"
    )
    .unwrap();
    for constant in &model.constants {
        if model
            .newtypes
            .iter()
            .any(|newtype| newtype.name == constant.ty)
        {
            writeln!(
                out,
                "        assert_eq!({}.0, {});",
                constant.name, constant.value
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "        assert_eq!({}, {});",
                constant.name, constant.value
            )
            .unwrap();
        }
    }
    for syscall in &model.syscalls {
        writeln!(
            out,
            "        assert_eq!(DW_SYSCALL_{}.0, 0x{:08x});",
            syscall.name.to_ascii_uppercase(),
            syscall.number
        )
        .unwrap();
    }
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    Ok(out)
}

pub(super) fn rust_value(ty: &str, value: i128, newtypes: &[Newtype]) -> String {
    if newtypes.iter().any(|item| item.name == ty) {
        format!("{ty}({value})")
    } else {
        value.to_string()
    }
}

pub(super) fn render_c(model: &Model) -> Result<String> {
    let mut out = generated_preamble("/*");
    // Close the deliberately simple block-comment preamble lines.
    out = out.replace("\n\n", " */\n\n").replace("\n/* Do", "\n * Do");
    writeln!(out, "#ifndef DEEPWYRM_ABI_GENERATED_H").unwrap();
    writeln!(out, "#define DEEPWYRM_ABI_GENERATED_H\n").unwrap();
    writeln!(out, "#include <stddef.h>").unwrap();
    writeln!(out, "#include <stdint.h>\n").unwrap();
    writeln!(out, "#if defined(__cplusplus)").unwrap();
    writeln!(out, "#define DW_STATIC_ASSERT static_assert").unwrap();
    writeln!(out, "#define DW_ALIGNOF alignof").unwrap();
    writeln!(out, "#else").unwrap();
    writeln!(out, "#define DW_STATIC_ASSERT _Static_assert").unwrap();
    writeln!(out, "#define DW_ALIGNOF _Alignof").unwrap();
    writeln!(out, "#endif\n").unwrap();
    writeln!(
        out,
        "#define DW_ABI_VERSION UINT32_C({})\n",
        model.abi.version
    )
    .unwrap();
    let layouts = type_layouts(&model.newtypes);
    for item in &model.newtypes {
        writeln!(out, "/* {} */", item.doc).unwrap();
        writeln!(out, "typedef {} {};\n", c_primitive(&item.base)?, item.name).unwrap();
        let (size, align) = layouts[&item.name];
        writeln!(
            out,
            "DW_STATIC_ASSERT(sizeof({}) == {}, \"{} size\");",
            item.name, size, item.name
        )
        .unwrap();
        writeln!(
            out,
            "DW_STATIC_ASSERT(DW_ALIGNOF({}) == {}, \"{} alignment\");\n",
            item.name, align, item.name
        )
        .unwrap();
    }
    for set in &model.value_sets {
        for item in &set.values {
            writeln!(out, "/* {} */", item.doc).unwrap();
            writeln!(
                out,
                "#define {}_{} (({})({}))",
                set.prefix, item.name, set.rust_type, item.value
            )
            .unwrap();
        }
        out.push('\n');
    }
    writeln!(out, "/* Mask of every DwRights bit known to ABI 0. */").unwrap();
    writeln!(
        out,
        "#define DW_RIGHTS_KNOWN_MASK ((DwRights)({}))",
        model.known_rights_mask
    )
    .unwrap();
    for entry in &model.object_rights {
        writeln!(
            out,
            "/* Compatible rights for the {} object type. */",
            entry.object
        )
        .unwrap();
        writeln!(
            out,
            "#define DW_OBJECT_COMPATIBLE_RIGHTS_{} ((DwRights)({}))",
            entry.object, entry.mask
        )
        .unwrap();
    }
    out.push('\n');
    writeln!(
        out,
        "static inline DwRights dw_object_compatible_rights(DwObjectType object_type) {{"
    )
    .unwrap();
    writeln!(out, "    switch (object_type) {{").unwrap();
    for entry in &model.object_rights {
        writeln!(
            out,
            "    case DW_OBJECT_TYPE_{}: return DW_OBJECT_COMPATIBLE_RIGHTS_{};",
            entry.object, entry.object
        )
        .unwrap();
    }
    writeln!(out, "    default: return (DwRights)0;").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}\n").unwrap();
    writeln!(
        out,
        "static inline int dw_rights_are_known(DwRights rights) {{"
    )
    .unwrap();
    writeln!(out, "    return (rights & ~DW_RIGHTS_KNOWN_MASK) == 0;").unwrap();
    writeln!(out, "}}\n").unwrap();
    writeln!(
        out,
        "static inline int dw_rights_are_compatible(DwObjectType object_type, DwRights rights) {{"
    )
    .unwrap();
    writeln!(
        out,
        "    DwRights compatible = dw_object_compatible_rights(object_type);"
    )
    .unwrap();
    writeln!(out, "    return (rights & ~compatible) == 0;").unwrap();
    writeln!(out, "}}\n").unwrap();
    writeln!(out, "/* Mask of every DwSignals bit known to ABI 0. */").unwrap();
    writeln!(
        out,
        "#define DW_SIGNALS_KNOWN_MASK ((DwSignals)({}))",
        model.known_signals_mask
    )
    .unwrap();
    for entry in &model.object_signals {
        writeln!(
            out,
            "/* Applicable wait signals for the {} object type. */",
            entry.object
        )
        .unwrap();
        writeln!(
            out,
            "#define DW_OBJECT_COMPATIBLE_SIGNALS_{} ((DwSignals)({}))",
            entry.object, entry.mask
        )
        .unwrap();
    }
    out.push('\n');
    writeln!(
        out,
        "static inline DwSignals dw_object_compatible_signals(DwObjectType object_type) {{"
    )
    .unwrap();
    writeln!(out, "    switch (object_type) {{").unwrap();
    for entry in &model.object_signals {
        writeln!(
            out,
            "    case DW_OBJECT_TYPE_{}: return DW_OBJECT_COMPATIBLE_SIGNALS_{};",
            entry.object, entry.object
        )
        .unwrap();
    }
    writeln!(out, "    default: return (DwSignals)0;").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}\n").unwrap();
    writeln!(
        out,
        "static inline int dw_signals_are_known(DwSignals signals) {{"
    )
    .unwrap();
    writeln!(out, "    return (signals & ~DW_SIGNALS_KNOWN_MASK) == 0;").unwrap();
    writeln!(out, "}}\n").unwrap();
    writeln!(out, "static inline int dw_signals_are_compatible(DwObjectType object_type, DwSignals signals) {{").unwrap();
    writeln!(
        out,
        "    DwSignals compatible = dw_object_compatible_signals(object_type);"
    )
    .unwrap();
    writeln!(out, "    return (signals & ~compatible) == 0;").unwrap();
    writeln!(out, "}}\n").unwrap();
    for constant in &model.constants {
        writeln!(out, "/* {} */", constant.doc).unwrap();
        writeln!(
            out,
            "#define {} (({})({}))",
            constant.name,
            c_named(&constant.ty)?,
            constant.value
        )
        .unwrap();
    }
    out.push('\n');
    for syscall in &model.syscalls {
        writeln!(out, "/* {} */", syscall.doc).unwrap();
        writeln!(
            out,
            "#define DW_SYSCALL_{} ((DwSyscallId)(UINT32_C(0x{:08x})))",
            syscall.name.to_ascii_uppercase(),
            syscall.number
        )
        .unwrap();
    }
    out.push('\n');

    for record in &model.records {
        writeln!(out, "/* {} */", record.doc).unwrap();
        writeln!(out, "typedef struct {} {{", record.name).unwrap();
        for field in &record.fields {
            writeln!(out, "    /* {} */", field.doc).unwrap();
            match &field.ty {
                FieldType::Named(name) => {
                    writeln!(out, "    {} {};", c_named(name)?, field.name).unwrap();
                }
                FieldType::Array(name, count) => {
                    writeln!(out, "    {} {}[{}];", c_named(name)?, field.name, count).unwrap();
                }
            }
        }
        writeln!(out, "}} {};", record.name).unwrap();
        writeln!(
            out,
            "#define {} ((uint32_t)({}))",
            record_size_constant(&record.name),
            record.size
        )
        .unwrap();
        writeln!(
            out,
            "DW_STATIC_ASSERT(sizeof({}) == {}, \"{} size\");",
            record.name, record.size, record.name
        )
        .unwrap();
        writeln!(
            out,
            "DW_STATIC_ASSERT(DW_ALIGNOF({}) == {}, \"{} alignment\");",
            record.name, record.align, record.name
        )
        .unwrap();
        for (field, offset) in record.fields.iter().zip(&record.offsets) {
            writeln!(
                out,
                "DW_STATIC_ASSERT(offsetof({}, {}) == {}, \"{}.{} offset\");",
                record.name, field.name, offset, record.name, field.name
            )
            .unwrap();
        }
        out.push('\n');
    }
    writeln!(out, "#undef DW_ALIGNOF").unwrap();
    writeln!(out, "#undef DW_STATIC_ASSERT\n").unwrap();
    writeln!(out, "#endif /* DEEPWYRM_ABI_GENERATED_H */").unwrap();
    Ok(out)
}

pub(super) fn c_primitive(name: &str) -> Result<&'static str> {
    match name {
        "u8" => Ok("uint8_t"),
        "u16" => Ok("uint16_t"),
        "u32" => Ok("uint32_t"),
        "u64" => Ok("uint64_t"),
        "i8" => Ok("int8_t"),
        "i16" => Ok("int16_t"),
        "i32" => Ok("int32_t"),
        "i64" => Ok("int64_t"),
        other => Err(Error::new(format!("unsupported C primitive `{other}`"))),
    }
}

pub(super) fn c_named(name: &str) -> Result<&str> {
    match name {
        "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64" => c_primitive(name),
        _ => Ok(name),
    }
}

fn rust_syscall_variant(name: &str) -> String {
    name.split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn rust_phase_variant(phase: &str) -> Result<&'static str> {
    match phase {
        "DW0-A" => Ok("Dw0A"),
        "DW0-B" => Ok("Dw0B"),
        "DW0-C" => Ok("Dw0C"),
        "DW0-D" => Ok("Dw0D"),
        "DW0-E" => Ok("Dw0E"),
        "DW0-F" => Ok("Dw0F"),
        "DW0-G" => Ok("Dw0G"),
        "DW0-H" => Ok("Dw0H"),
        other => Err(Error::new(format!(
            "unsupported syscall implementation phase `{other}`"
        ))),
    }
}

pub(super) fn render_kernel_dispatch(model: &Model) -> Result<String> {
    let mut out = generated_preamble("//");
    writeln!(
        out,
        "/// Build-phase classification used by kernel dispatch; this is generator metadata, not native ABI."
    )
    .unwrap();
    writeln!(out, "#[repr(u8)]").unwrap();
    writeln!(
        out,
        "#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]"
    )
    .unwrap();
    writeln!(out, "pub enum DwSyscallImplementationPhase {{").unwrap();
    for (index, variant) in [
        "Dw0A", "Dw0B", "Dw0C", "Dw0D", "Dw0E", "Dw0F", "Dw0G", "Dw0H",
    ]
    .into_iter()
    .enumerate()
    {
        writeln!(out, "    {variant} = {index},").unwrap();
    }
    writeln!(out, "}}\n").unwrap();
    writeln!(out, "impl DwSyscallImplementationPhase {{").unwrap();
    writeln!(
        out,
        "    pub const fn is_active_through(self, through: Self) -> bool {{ (self as u8) <= (through as u8) }}"
    )
    .unwrap();
    writeln!(out, "}}\n").unwrap();

    writeln!(
        out,
        "/// String-free schema-owned syscall identity for kernel routing."
    )
    .unwrap();
    writeln!(out, "#[derive(Clone, Copy, Debug, Eq, PartialEq)]").unwrap();
    writeln!(out, "pub enum DwKnownSyscall {{").unwrap();
    for syscall in &model.syscalls {
        writeln!(out, "    {},", rust_syscall_variant(&syscall.name)).unwrap();
    }
    writeln!(out, "}}\n").unwrap();
    writeln!(out, "impl DwKnownSyscall {{").unwrap();
    writeln!(
        out,
        "    pub const fn from_id(id: DwSyscallId) -> Option<Self> {{"
    )
    .unwrap();
    writeln!(out, "        match id.0 {{").unwrap();
    for syscall in &model.syscalls {
        writeln!(
            out,
            "            0x{:08x} => Some(Self::{}),",
            syscall.number,
            rust_syscall_variant(&syscall.name)
        )
        .unwrap();
    }
    writeln!(out, "            _ => None,").unwrap();
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}\n").unwrap();

    writeln!(out, "    pub const fn id(self) -> DwSyscallId {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for syscall in &model.syscalls {
        writeln!(
            out,
            "            Self::{} => DwSyscallId(0x{:08x}),",
            rust_syscall_variant(&syscall.name),
            syscall.number
        )
        .unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}\n").unwrap();

    writeln!(
        out,
        "    pub const fn implementation_phase(self) -> DwSyscallImplementationPhase {{"
    )
    .unwrap();
    writeln!(out, "        match self {{").unwrap();
    for syscall in &model.syscalls {
        writeln!(
            out,
            "            Self::{} => DwSyscallImplementationPhase::{},",
            rust_syscall_variant(&syscall.name),
            rust_phase_variant(&syscall.phase)?
        )
        .unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}\n").unwrap();

    writeln!(out, "    pub const fn argument_count(self) -> u8 {{").unwrap();
    writeln!(out, "        match self {{").unwrap();
    for syscall in &model.syscalls {
        writeln!(
            out,
            "            Self::{} => {},",
            rust_syscall_variant(&syscall.name),
            syscall.arguments.len()
        )
        .unwrap();
    }
    writeln!(out, "        }}").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}\n").unwrap();
    Ok(out)
}

pub(super) fn render_x86_64_syscall_veneer(model: &Model) -> Result<String> {
    // Model loading already rejects any convention that does not match this audited veneer.
    let mut out = generated_preamble("#");
    writeln!(out, ".text").unwrap();
    writeln!(out, ".p2align 4").unwrap();
    writeln!(out, ".globl dw_syscall6").unwrap();
    writeln!(out, ".type dw_syscall6,@function").unwrap();
    writeln!(out, "dw_syscall6:").unwrap();
    writeln!(
        out,
        "    # SysV: number,a0,a1,a2,a3,a4 in registers; a5 at 8(%rsp)."
    )
    .unwrap();
    writeln!(
        out,
        "    # Deepwyrm raw: RAX=number, RDI,RSI,RDX,R10,R8,R9=args."
    )
    .unwrap();
    writeln!(out, "    movq %rdi, %rax").unwrap();
    writeln!(out, "    movq %rsi, %rdi").unwrap();
    writeln!(out, "    movq %rdx, %rsi").unwrap();
    writeln!(out, "    movq %rcx, %rdx").unwrap();
    writeln!(out, "    movq %r8, %r10").unwrap();
    writeln!(out, "    movq %r9, %r8").unwrap();
    writeln!(out, "    movq 8(%rsp), %r9").unwrap();
    writeln!(out, "    syscall").unwrap();
    writeln!(out, "    retq").unwrap();
    writeln!(out, ".size dw_syscall6, .-dw_syscall6").unwrap();
    writeln!(out, ".section .note.GNU-stack,\"\",@progbits").unwrap();
    let _ = model;
    Ok(out)
}

pub(super) fn render_dispatch_metadata(model: &Model) -> Result<String> {
    let mut out = generated_preamble("//");
    writeln!(out, "#[derive(Clone, Copy, Debug, Eq, PartialEq)]").unwrap();
    writeln!(out, "pub struct DwSyscallDispatchMetadata {{").unwrap();
    writeln!(out, "    pub number: u32,").unwrap();
    writeln!(out, "    pub name: &'static str,").unwrap();
    writeln!(out, "    pub implementation_phase: &'static str,").unwrap();
    writeln!(out, "    pub argument_count: u8,").unwrap();
    writeln!(out, "}}\n").unwrap();
    writeln!(
        out,
        "pub const DW_SYSCALL_DISPATCH_METADATA: &[DwSyscallDispatchMetadata] = &["
    )
    .unwrap();
    for syscall in &model.syscalls {
        writeln!(out, "    DwSyscallDispatchMetadata {{").unwrap();
        writeln!(out, "        number: 0x{:08x},", syscall.number).unwrap();
        writeln!(out, "        name: \"{}\",", syscall.name).unwrap();
        writeln!(out, "        implementation_phase: \"{}\",", syscall.phase).unwrap();
        writeln!(out, "        argument_count: {},", syscall.arguments.len()).unwrap();
        writeln!(out, "    }},").unwrap();
    }
    writeln!(out, "];\n").unwrap();
    writeln!(
        out,
        "pub const DW_UNKNOWN_SYSCALL_STATUS_NAME: &str = \"NOT_SUPPORTED\";"
    )
    .unwrap();
    Ok(out)
}

pub(super) fn render_wrapper_metadata(model: &Model) -> Result<String> {
    let mut out = generated_preamble("//");
    writeln!(
        out,
        "pub const DW_SYSCALL_INSTRUCTION: &str = \"{}\";",
        model.abi.instruction
    )
    .unwrap();
    writeln!(
        out,
        "pub const DW_SYSCALL_NUMBER_REGISTER: &str = \"{}\";",
        model.abi.number_register
    )
    .unwrap();
    writeln!(
        out,
        "pub const DW_SYSCALL_RESULT_REGISTER: &str = \"{}\";",
        model.abi.result_register
    )
    .unwrap();
    writeln!(
        out,
        "pub const DW_SYSCALL_CLOBBERS: &str = \"{}\";",
        model.abi.clobbers
    )
    .unwrap();
    writeln!(
        out,
        "pub const DW_SYSCALL_RESULT_RULE: &str = \"{}\";\n",
        model.abi.result_rule
    )
    .unwrap();
    writeln!(out, "#[derive(Clone, Copy, Debug, Eq, PartialEq)]").unwrap();
    writeln!(out, "pub struct DwSyscallArgumentMetadata {{").unwrap();
    writeln!(out, "    pub syscall_number: u32,").unwrap();
    writeln!(out, "    pub index: u8,").unwrap();
    writeln!(out, "    pub register: &'static str,").unwrap();
    writeln!(out, "    pub name: &'static str,").unwrap();
    writeln!(out, "    pub abi_type: &'static str,").unwrap();
    writeln!(out, "    pub direction: &'static str,").unwrap();
    writeln!(out, "    pub required_object_type: &'static str,").unwrap();
    writeln!(out, "    pub required_rights: &'static str,").unwrap();
    writeln!(out, "}}\n").unwrap();
    writeln!(
        out,
        "pub const DW_SYSCALL_ARGUMENT_METADATA: &[DwSyscallArgumentMetadata] = &["
    )
    .unwrap();
    for syscall in &model.syscalls {
        for (index, argument) in syscall.arguments.iter().enumerate() {
            writeln!(out, "    DwSyscallArgumentMetadata {{").unwrap();
            writeln!(out, "        syscall_number: 0x{:08x},", syscall.number).unwrap();
            writeln!(out, "        index: {index},").unwrap();
            writeln!(
                out,
                "        register: \"{}\",",
                model.abi.argument_registers[index]
            )
            .unwrap();
            writeln!(out, "        name: \"{}\",", argument.name).unwrap();
            writeln!(out, "        abi_type: \"{}\",", argument.ty).unwrap();
            writeln!(out, "        direction: \"{}\",", argument.direction).unwrap();
            writeln!(
                out,
                "        required_object_type: \"{}\",",
                argument.object_type
            )
            .unwrap();
            writeln!(
                out,
                "        required_rights: \"{}\",",
                if argument.rights.is_empty() {
                    "NONE".to_owned()
                } else {
                    argument.rights.join("+")
                }
            )
            .unwrap();
            writeln!(out, "    }},").unwrap();
        }
    }
    writeln!(out, "];\n").unwrap();
    Ok(out)
}

pub(super) fn render_markdown(model: &Model) -> Result<String> {
    let mut out = generated_preamble("<!--");
    out = out.replace("\n\n", " -->\n\n").replace("\n<!-- Do", "\nDo");
    writeln!(
        out,
        "# {} native ABI {}\n",
        model.abi.name, model.abi.version
    )
    .unwrap();
    writeln!(out, "The canonical schema is under `abi/schema`. Numeric namespace values remain representable even when a consumer does not recognize them; operations reject unsupported required values and flags explicitly.\n").unwrap();
    writeln!(out, "## Raw x86_64 syscall convention\n").unwrap();
    writeln!(out, "- Instruction: `{}`", model.abi.instruction).unwrap();
    writeln!(
        out,
        "- Number: `{}` (`DwSyscallId`, zero reserved)",
        model.abi.number_register
    )
    .unwrap();
    writeln!(
        out,
        "- Arguments: `{}`",
        model.abi.argument_registers.join(", ")
    )
    .unwrap();
    writeln!(
        out,
        "- Result: `{}`; {}",
        model.abi.result_register, model.abi.result_rule
    )
    .unwrap();
    writeln!(out, "- Clobbers: `{}`\n", model.abi.clobbers).unwrap();
    writeln!(out, "## Freestanding x86_64 syscall veneer\n").unwrap();
    writeln!(out, "`syscall_veneer_x86_64.S` exports `dw_syscall6(number, arg0, arg1, arg2, arg3, arg4, arg5)` as a libc-independent SysV link veneer for freestanding native tests/runtime code. It rearranges the ordinary function-call registers into the raw Deepwyrm syscall convention, executes `SYSCALL`, and returns the sign-extended `DwStatus` in `RAX`. It is a native ABI binding, not libc.\n").unwrap();
    writeln!(
        out,
        "## Rights-input invariant\n\n{}\n",
        model.abi.rights_input_rule
    )
    .unwrap();
    writeln!(out, "## Object-right compatibility\n").unwrap();
    writeln!(out, "`DW_RIGHTS_KNOWN_MASK` is `{}`. Zero is structurally known/compatible; operations that request new authority apply the separate nonzero-rights rule. Sentinel, reserved, and unknown object types have a compatible-rights mask of zero.\n", model.known_rights_mask).unwrap();
    writeln!(
        out,
        "| Object | Generated mask | Rights | Value |\n|---|---|---|---:|"
    )
    .unwrap();
    for entry in &model.object_rights {
        writeln!(
            out,
            "| `DW_OBJECT_TYPE_{}` | `DW_OBJECT_COMPATIBLE_RIGHTS_{}` | `{}` | `{}` |",
            entry.object,
            entry.object,
            entry
                .rights
                .iter()
                .map(|right| format!("DW_RIGHT_{right}"))
                .collect::<Vec<_>>()
                .join(" + "),
            entry.mask
        )
        .unwrap();
    }
    out.push('\n');
    writeln!(out, "## Object-signal compatibility\n").unwrap();
    writeln!(out, "`DW_SIGNALS_KNOWN_MASK` is `{}`. Applicability is generated from each signal's `applies_to` schema field; zero is structurally compatible but wait operations separately require nonzero desired signals.\n", model.known_signals_mask).unwrap();
    writeln!(
        out,
        "| Object | Generated mask | Signals | Value |\n|---|---|---|---:|"
    )
    .unwrap();
    for entry in &model.object_signals {
        let names = if entry.signals.is_empty() {
            "NONE".to_owned()
        } else {
            entry
                .signals
                .iter()
                .map(|signal| format!("DW_SIGNAL_{signal}"))
                .collect::<Vec<_>>()
                .join(" + ")
        };
        writeln!(
            out,
            "| `DW_OBJECT_TYPE_{}` | `DW_OBJECT_COMPATIBLE_SIGNALS_{}` | `{}` | `{}` |",
            entry.object, entry.object, names, entry.mask
        )
        .unwrap();
    }
    out.push('\n');
    for set in &model.value_sets {
        writeln!(out, "## {}\n", title(&set.section)).unwrap();
        writeln!(
            out,
            "| Name | Value | Meaning | Notes |\n|---|---:|---|---|"
        )
        .unwrap();
        for item in &set.values {
            writeln!(
                out,
                "| `{}_{}` | `{}` | {} | {} |",
                set.prefix, item.name, item.value, item.doc, item.extra
            )
            .unwrap();
        }
        out.push('\n');
    }
    writeln!(out, "## Constants\n").unwrap();
    writeln!(out, "| Name | Type | Value | Meaning |\n|---|---|---:|---|").unwrap();
    for constant in &model.constants {
        writeln!(
            out,
            "| `{}` | `{}` | `{}` | {} |",
            constant.name, constant.ty, constant.value, constant.doc
        )
        .unwrap();
    }
    out.push('\n');
    writeln!(out, "## Records\n").unwrap();
    for record in &model.records {
        writeln!(
            out,
            "### `{}`\n\n{} Size {}, alignment {}.\n",
            record.name, record.doc, record.size, record.align
        )
        .unwrap();
        writeln!(
            out,
            "| Offset | Field | Type | Meaning |\n|---:|---|---|---|"
        )
        .unwrap();
        for (field, offset) in record.fields.iter().zip(&record.offsets) {
            writeln!(
                out,
                "| {} | `{}` | `{}` | {} |",
                offset,
                field.name,
                field.ty.rust(),
                field.doc
            )
            .unwrap();
        }
        out.push('\n');
    }
    writeln!(out, "## Object-info topics\n").unwrap();
    writeln!(out, "Unknown topics return `DW_STATUS_NOT_SUPPORTED`.\n").unwrap();
    writeln!(out, "| Topic | Accepted objects | Result | Incompatible object | Meaning |\n|---|---|---|---|---|").unwrap();
    for topic in &model.object_info_topics {
        writeln!(
            out,
            "| `{}` | `{}` | `{}` | `DW_STATUS_{}` | {} |",
            topic.topic, topic.accepted_objects, topic.result, topic.incompatible_status, topic.doc
        )
        .unwrap();
    }
    out.push('\n');
    writeln!(out, "## Syscalls\n").unwrap();
    writeln!(out, "Unknown or debug-disabled syscall IDs return `DW_STATUS_NOT_SUPPORTED`. Fixed-size V1 output pointers write exactly `sizeof(V1)` on success.\n").unwrap();
    for syscall in &model.syscalls {
        writeln!(
            out,
            "### `0x{:08x}` `{}` ({})\n\n{}\n",
            syscall.number, syscall.name, syscall.phase, syscall.doc
        )
        .unwrap();
        if syscall.arguments.is_empty() {
            writeln!(out, "No register arguments.\n").unwrap();
        } else {
            writeln!(out, "| Register | Argument | Type | Direction | Object | Rights |\n|---|---|---|---|---|---|").unwrap();
            for (index, argument) in syscall.arguments.iter().enumerate() {
                writeln!(
                    out,
                    "| `{}` | `{}` | `{}` | {} | {} | {} |",
                    model.abi.argument_registers[index],
                    argument.name,
                    argument.ty,
                    argument.direction,
                    argument.object_type,
                    if argument.rights.is_empty() {
                        "NONE".to_owned()
                    } else {
                        argument.rights.join("+")
                    }
                )
                .unwrap();
            }
            out.push('\n');
        }
    }
    Ok(out)
}

pub(super) fn title(section: &str) -> String {
    let mut result = String::new();
    for (index, word) in section.split('_').enumerate() {
        if index != 0 {
            result.push(' ');
        }
        let mut chars = word.chars();
        if let Some(first) = chars.next() {
            result.push(first.to_ascii_uppercase());
            result.extend(chars);
        }
    }
    result
}

pub(super) fn render_readme() -> String {
    "# Generated Deepwyrm ABI artifacts\n\nThis directory is owned by `abi-gen`. Do not edit generated files directly.\n\nGenerated surfaces include the Rust/C ABI definitions, string-free kernel syscall routing, host-side dispatch/wrapper metadata, the libc-independent x86_64 syscall veneer, and ABI documentation.\n\nFrom the Deepwyrm repository root:\n\n```text\ncargo xtask abi generate\ncargo xtask abi check\n```\n\n`check` regenerates the expected files in memory and fails on missing, stale, or unexpected output.\n".to_owned()
}

pub(super) fn record_size_constant(name: &str) -> String {
    format!("{}_SIZE", camel_to_upper_snake(name))
}

pub(super) fn camel_to_upper_snake(name: &str) -> String {
    let mut out = String::new();
    let mut previous_lower_or_digit = false;
    for character in name.chars() {
        if character.is_ascii_uppercase() && previous_lower_or_digit {
            out.push('_');
        }
        out.push(character.to_ascii_uppercase());
        previous_lower_or_digit = character.is_ascii_lowercase() || character.is_ascii_digit();
    }
    out
}
